name: Build Docker and Optional Push

on:
  push:
    branches: [main, dev, demo]
  pull_request:
    branches: [main, dev, demo]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        if: ${{ github.ref_name == 'main' }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Log in to Azure Container Registry (Dev/Demo)
        if: ${{ github.ref_name == 'dev' || github.ref_name == 'demo' }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_DEV_LOGIN_SERVER }}
          username: ${{ secrets.ACR_DEV_USERNAME }}
          password: ${{ secrets.ACR_DEV_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get registry
        id: registry
        run: echo "registry=${{ github.ref_name == 'main' && secrets.ACR_LOGIN_SERVER || secrets.ACR_DEV_LOGIN_SERVER }}" >> $GITHUB_OUTPUT

      - name: Determine Tag Name Based on Branch
        id: determine_tag
        run: echo "tagname=${{ github.ref_name == 'main' && 'latest' || github.ref_name == 'dev' && 'dev' || github.ref_name == 'demo' && 'demo' || github.head_ref || 'default' }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image and optionally push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: WebApp.Dockerfile
          push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo' }}
          tags: |
            ${{ steps.registry.outputs.registry }}/webapp:${{ steps.determine_tag.outputs.tagname }}
            ${{ steps.registry.outputs.registry }}/webapp:${{ steps.determine_tag.outputs.tagname }}_${{ steps.date.outputs.date }}_${{ github.run_number }}
